# Generated by Django 3.2.7 on 2021-11-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=32)),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonaSoporte',
        ),
        migrations.DeleteModel(
            name='PQR',
        ),
        migrations.AddField(
            model_name='horarios',
            name='id_sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.sedes'),
        ),
    ]
