# Generated by Django 3.2.7 on 2021-11-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0004_auto_20211118_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='hora_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='hora_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planes',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedes',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
