# Generated by Django 3.2.7 on 2021-11-18 21:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0002_sedes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sedes',
            new_name='Sede',
        ),
    ]
